// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnrrPImxS67srKbLweQ8q0j_CicDPlbsE',
    appId: '1:71092652279:web:cab3efd96581b218b6abf2',
    messagingSenderId: '71092652279',
    projectId: 'projeto-flutter-gustavo',
    authDomain: 'projeto-flutter-gustavo.firebaseapp.com',
    storageBucket: 'projeto-flutter-gustavo.firebasestorage.app',
    measurementId: 'G-GNNV6X1PRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiFicMvdrl649clLitz69fmQ0iD8gHJH0',
    appId: '1:71092652279:android:cadff76c03b4432bb6abf2',
    messagingSenderId: '71092652279',
    projectId: 'projeto-flutter-gustavo',
    storageBucket: 'projeto-flutter-gustavo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq_WXQFD9nlUHRDawAZlFUCVbRHTNiH3U',
    appId: '1:71092652279:ios:ea7e31121428eaf4b6abf2',
    messagingSenderId: '71092652279',
    projectId: 'projeto-flutter-gustavo',
    storageBucket: 'projeto-flutter-gustavo.firebasestorage.app',
    iosBundleId: 'com.example.telaLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq_WXQFD9nlUHRDawAZlFUCVbRHTNiH3U',
    appId: '1:71092652279:ios:ea7e31121428eaf4b6abf2',
    messagingSenderId: '71092652279',
    projectId: 'projeto-flutter-gustavo',
    storageBucket: 'projeto-flutter-gustavo.firebasestorage.app',
    iosBundleId: 'com.example.telaLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnrrPImxS67srKbLweQ8q0j_CicDPlbsE',
    appId: '1:71092652279:web:4e533c1eefa1bbf7b6abf2',
    messagingSenderId: '71092652279',
    projectId: 'projeto-flutter-gustavo',
    authDomain: 'projeto-flutter-gustavo.firebaseapp.com',
    storageBucket: 'projeto-flutter-gustavo.firebasestorage.app',
    measurementId: 'G-X020GD740P',
  );
}
